### ISSUE TITLE
I suggest change python/ipython to python3/ipython3 for using Python3.5 obviously in importer.sh

### ISSUE THREAD

**Issue by TaihuLight** [albanie/pytorch-mcn#2] opened 2018-01-17 00:41 UTC
Steps for Convert models from MatConvNet to PyTorch  with pytorch-mcn
(1)run pytorch-mcn/compare/ensure_dags.m in matlab to convert models to dagnn... 
(2)edit and run shell script importer.sh to Convert models from MatConvNet to PyTorch  with pytorch-mcn
(3)the results
Saving imported model definition to ./models/resnext_50_32x4d_pt_mcn.py
Saving imported weights to ./models/resnext_50_32x4d_pt_mcn.pth

Bugs?
(1)Due to the default Python is 2.7 on the most Linux OS, and Python3 means Python3.5 on the  the most Linux OS. Thus, I suggest change the python/ipython to python3/ipython3 for using Python3.5 obviously in importer.sh.
(2) The waning "skipping conv bias term"
skipping conv bias term
skipping conv bias term
skipping conv bias term
skipping conv bias term
skipping conv bias term
(3) Errors
    > /home/chengzi/Downloads/pytorch-mcn/python/ptmcn_utils.py(66)conv2d_mod()
     65         if not valid_conv_groups: import ipdb ; ipdb.set_trace()
---> 66         assert valid_conv_groups, msg
     67         num_groups = int(in_ch / fsize[2])

**Comment by albanie** [comment] 2018-01-17 09:19
(1) Changing the `python` command to `python3` is a good suggestion. 
(2) The `skipping conv bias term` is not a bug, it's simply a notification to the user that there are no bias parameters associated with the corresponding convolutional weights.  However, this could be restricted to a `verbose` mode.
(3) This error is a safety check which fails if the tool is not able to determine the convolutional weight shape.

**Comment by albanie** [comment] 2018-08-13 18:07
Am closing, but feel free to re-open if needed.

**Closed as completed by albanie** 2018-08-13 18:07 UTC
